BUILD.md
=> Created BUILD.md with build instructions

NorthstarDedicatedTest/logging.cpp
Make timestamp `year-month-day` instead of `day-month-year`. 
The old format is bothering me more than it should :P
=> Make timestamp year-month-day

LauncherInjector/resources.rc
=> Add version resource

NorthstarDedicatedTest/dedicated.cpp
=> Limit title update interval to 500ms

BUILD.md
=> Update link in BUILD.MD

NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj, NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj.filters, NorthstarDedicatedTest/bitbuf.h, NorthstarDedicatedTest/dllmain.cpp, NorthstarDedicatedTest/logging.cpp, NorthstarDedicatedTest/logging.h
CenterPrintAll serverside function now actually works, as well as some native engine prints (unknown command, some other commands etc.)
also adds a game-compatible bitbuf classes (read and write)
=> Add TextMsg logging

NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj, NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj.filters, NorthstarDedicatedTest/bansystem.cpp, NorthstarDedicatedTest/configurables.cpp, NorthstarDedicatedTest/configurables.h, NorthstarDedicatedTest/dllmain.cpp, NorthstarDedicatedTest/filesystem.cpp, NorthstarDedicatedTest/keyvalues.cpp, NorthstarDedicatedTest/logging.cpp, NorthstarDedicatedTest/modmanager.cpp, NorthstarDedicatedTest/modmanager.h, NorthstarDedicatedTest/pdef.h, NorthstarDedicatedTest/scriptsrson.h, NorthstarDedicatedTest/serverauthentication.cpp
Added command line option for custom northstar directory
https://github.com/orgs/R2Northstar/projects/1#card-76312632
=> Added command line option for custom northstar directory

NorthstarDedicatedTest/scriptsrson.cpp, NorthstarDedicatedTest/scriptsrson.h
Basically i made an oopsie which caused a path to be read before it was initialised, causing northstar to try to delete a non-existent file, resulting in a crash
=> Correct a bug in my preview PR

NorthstarDedicatedTest/pdef.cpp, NorthstarDedicatedTest/pdef.h
=> I Hate C++

NorthstarDedicatedTest/serverauthentication.cpp
This may not seem like much to a passing observer, but this commit took me 30 hours of blood, sweat, tears, IDA debugging, server crashes, and insanity.
Should be paired with a commit in Mods
=> Added code for chathooks

NorthstarDedicatedTest/buildainfile.cpp
Done by using clang-format
Should fix format-check CI error
=> Fix formatting/CI

NorthstarDedicatedTest/buildainfile.cpp
=> Fix formatting

LauncherInjector/main.cpp, NorthstarDedicatedTest/hooks.cpp
Autogenerate `ns_startup_args.txt` and add flag to bypass `ns_startup_args.txt`
=> Startup args for r2modman

LauncherInjector/main.cpp, NorthstarDedicatedTest/scriptservertoclientstringcommand.cpp
=> Allow origin to start in the background

NorthstarDedicatedTest/plugins.cpp
Related to https://github.com/R2Northstar/NorthstarMods/pull/277
=> Update `NSUpdateGameStateClient` to include `maxPlayers`

NorthstarDedicatedTest/audio.cpp, NorthstarDedicatedTest/audio.h
functionally this works from what i've tested and removes alot of the hitching on startup from audio loads, however there's probably a bunch of ways it could be improved before merging
=> add audio changes

NorthstarDedicatedTest/modmanager.cpp, NorthstarDedicatedTest/modmanager.h, NorthstarDedicatedTest/rpakfilesystem.cpp
adds support for loading mod map rpaks, mod stbsps, and a few small fixes to modded rpak load logic
=> various rpak loading changes

NorthstarDedicatedTest/dedicated.cpp, NorthstarDedicatedTest/rpakfilesystem.cpp, NorthstarDedicatedTest/rpakfilesystem.h
adds support for unloading mod rpaks, fixes a bug with loading entirely custom mod rpaks, and prevents all unnecessary rpaks from being loaded on dedicated servers
=> more changes to mod rpak loading

NorthstarDedicatedTest/dllmain.cpp
Should help sorting out old logs
=> Write launcher version to log file

NorthstarDedicatedTest/serverauthentication.cpp
Should help with getting a clearer picture regarding UID spoofing attacks.
=> Log UID in a variety of places during auth process

NorthstarDedicatedTest/serverauthentication.cpp
NVIDIA/open-gpu-kernel-modules#8 moment
=> Fix typo in UID logs

NorthstarDedicatedTest/miscserverscript.cpp
Adds `bool function NSIsDedicated()` to server vm
=> Expose IsDedicated on server vm

NorthstarDedicatedTest/ExploitFixes.cpp, NorthstarDedicatedTest/ExploitFixes.h, NorthstarDedicatedTest/dllmain.cpp
The KHook version did not hook the Function correctly.
=> Switch IsValveMod back to use a EnablerHook

NorthstarDedicatedTest/ExploitFixes.cpp
Move Include of "gameutils.h" in ExpoitFixes to top of file
=> Move #include top of file in ExploitFixes

NorthstarDedicatedTest/scriptjson.cpp, NorthstarDedicatedTest/squirrel.cpp
Fixed Issues from #172 
> Fixed using Server newTable in Client Function
> Fixed Client newTable using wrong offset
=> Fix a few issues with Json implementation to Squirrel VM

.github/pull_request_template.md, .github/workflows/ci.yml, NorthstarDLL/ns_startup_args.txt, NorthstarDLL/ns_startup_args_dedi.txt, NorthstarLauncher/ns_startup_args.txt, NorthstarLauncher/ns_startup_args_dedi.txt
- PR template
- CI config
- Delete startup args txts (shouldn't be in there)
=> Add some changes from main to refactor

NorthstarDLL/audio.cpp, NorthstarDLL/debugoverlay.cpp, NorthstarDLL/dedicated.cpp, NorthstarDLL/dedicated.h, NorthstarDLL/hooks.cpp, NorthstarDLL/logging.cpp, NorthstarDLL/miscclientfixes.cpp, NorthstarDLL/miscserverscript.cpp, NorthstarDLL/rpakfilesystem.cpp, NorthstarDLL/serverauthentication.cpp
Another change from big-refactor
=> Rename `IsDedicated()` to `IsDedicatedServer()`

NorthstarLauncher/main.cpp, README.md
indentation fix
fixes clang-format command in readme
=> Refactor cleanup

loader_launcher_proxy/Memory.h, loader_launcher_proxy/dllmain.cpp, loader_launcher_proxy/framework.h, loader_launcher_proxy/pch.h
Reverts formatting to how it is on main
=> More formatting stuff

NorthstarDLL/bansystem.cpp, NorthstarDLL/modmanager.cpp, NorthstarDLL/playlist.cpp, NorthstarDLL/serverauthentication.cpp
=> Standardise concommand func naming in C++

NorthstarDLL/clientauthhooks.cpp, NorthstarDLL/exploitfixes.cpp
=> Clear token when not needed anymore

NorthstarDLL/r2engine.h
Otherwise players joining get "Authentication  Failed"
```
[2022-10-17 00:57:32.764] [error] Failed reading masterserver response: got fastify error response
[2022-10-17 00:57:32.764] [error] {"success":false,"error":{"enum":"JSON_PARSE_ERROR","msg":"Error parsing json response"}}
```
=> Change PERSISTENCE_MAX_SIZE to fix player authentication

NorthstarDLL/clientvideooverrides.cpp
=> Fix using wrong dll load for patching bik loading

NorthstarDLL/limits.cpp
this cvar wasn't read properly in refactor, so connecting with data_block_enabled 1 would crash due to reading a null cvar
=> fix reading of cvar net_data_block_enabled

NorthstarDLL/crashhandler.cpp
The last 4 frames of the callstack will always be calls to the crash handler, and should be ignored, as they have no relevance to the actual crash.
This simply hides all stackframes until we find the one that matches the location of the crash.
supercedes #157
=> Fix bug with crashhandler

NorthstarDLL/dedicated.cpp, NorthstarDLL/logging.cpp
Status_ConMsg's hooks were set to apply on client only, this fixes this
=> Fix `status` hooks

NorthstarDLL/serverauthentication.cpp
Bob forgot to add this check in refactor
=> Fix player count in server presence

NorthstarDLL/serverauthentication.cpp
=> Fix player count server presence (again)

NorthstarDLL/NorthstarDLL.vcxproj.filters
=> fix accidentally broken project filters from merge conflict

NorthstarDLL/clientchathooks.cpp
=> Fix broken chat hooks due to missing AUTOHOOK_DISPATCH()

NorthstarDLL/NorthstarDLL.vcxproj, NorthstarDLL/NorthstarDLL.vcxproj.filters, NorthstarDLL/clientchathooks.cpp, NorthstarDLL/hoststate.cpp, NorthstarDLL/scriptservertoclientstringcommand.cpp, NorthstarDLL/serverchathooks.cpp, NorthstarDLL/squirrel.cpp, NorthstarDLL/squirrel.h, NorthstarDLL/squirrelclasstypes.h, NorthstarDLL/squirreldatatypes.h
Adds `call` and `schedule_call` with completely automatic variadic argument pushing and threadsafe asynchronous calls
Depends on https://github.com/R2Northstar/NorthstarMods/pull/525
=> Squirrel bridge v3

.github/workflows/ci.yml
Old version is being deprecated by GitHub
=> Update deprecated Actions

NorthstarDLL/dllmain.cpp, NorthstarDLL/squirrel.cpp, NorthstarDLL/squirrel.h
Fixes a bug where client squirrel managers were not initialised on server and vice-versa.
=> Pre-init squirrel managers

NorthstarDLL/hooks.cpp
=> Update exit value in hooks to valid code

NorthstarDLL/dllmain.cpp, NorthstarDLL/logging.h, NorthstarDLL/loghooks.cpp, NorthstarDLL/squirrel.cpp, NorthstarDLL/squirrel.h
Logs when failing to look up function on Squirrel manager call.
=> Log function lookup failure on Call

NorthstarDLL/squirrel/squirrel.h
Co-authored-by: Maya <RoyalBlue1@users.noreply.github.com>
Fix vectors being pushed to stack incorrectly
idk ask @RoyalBlue1 
needed for #387
=> push vectors to stack correctly

NorthstarDLL/scripts/client/cursorposition.cpp
Remove leftover debug print introduced in #387
=> remove debug logging

NorthstarDLL/NorthstarDLL.vcxproj.filters
oops, filters are broken again due to a missing </ClInclude>, this fixes them
=> fix broken filters

NorthstarDLL/mods/modmanager.cpp
Before:
```json
{
"Northstar.Client": true, "Northstar.CustomServers": true,  "Northstar.Custom": true
}
```
After:
```json
{
"Northstar.Client": true,
"Northstar.CustomServers": true,
"Northstar.Custom": true
}
```
=> Format content of `enabledmods.json`

NorthstarDLL/server/auth/bansystem.cpp
pragma is only for header files
=> Remove pragma once from source file

NorthstarDLL/CMakeLists.txt, NorthstarDLL/core/convar/concommand.cpp, NorthstarDLL/core/convar/convar.cpp, NorthstarDLL/core/filesystem/filesystem.cpp, NorthstarDLL/core/filesystem/rpakfilesystem.cpp, NorthstarDLL/core/hooks.cpp, NorthstarDLL/core/hooks.h, NorthstarDLL/core/math/vector.h, NorthstarDLL/core/tier0.h, NorthstarDLL/dedicated/dedicated.cpp, NorthstarDLL/engine/r2engine.h, NorthstarDLL/logging/sourceconsole.cpp, NorthstarDLL/masterserver/masterserver.cpp, NorthstarDLL/plugins/plugins.cpp, NorthstarDLL/squirrel/squirrel.h, NorthstarLauncher/CMakeLists.txt, loader_wsock32_proxy/CMakeLists.txt, loader_wsock32_proxy/loader.cpp
Cleaning up a bunch of code to be compatible with other compilers and systems.
=> Code cleaning

.gitattributes
Applies missing change from #491 as mentioned in https://github.com/R2Northstar/NorthstarLauncher/pull/491#issuecomment-1613980470
=> Update gitattributes vendored code path

NorthstarDLL/mods/modmanager.cpp
was told to separate it this from #525
=> Warn about the package dir, not the mod dir

NorthstarDLL/util/printmaps.cpp
#529 breaks Docker image as per https://github.com/pg9182/northstar-dedicated/issues/70
As such we should revert the change until we can figure out the reason for breakage.
=> Revert "Add a safeguard to map command"

.github/workflows/add-to-project.yml
Hopefully this PR should add new issues and PRs to the project board automatically (so that i dont have to do it manually)
=> Add workflow for adding PRs and Issues to the project board

NorthstarDLL/core/structs.h
Here be dragons
This behavior is a lot more reliable and less dependent on how constants are represented during the preprocessing step.
=> Replace field preprocessors with less hacky solutions

.github/workflows/add-to-project.yml
Same as https://github.com/R2Northstar/NorthstarMods/pull/753 which seems to be working just fine
=> Run add-to-project on new PRs

NorthstarDLL/squirrel/squirrelautobind.h
=> Fix SERVER | CLIENT context specifier error

primedev/masterserver/masterserver.cpp, primedev/mods/autodownload/moddownloader.cpp, primedev/util/utils.h
These things are kinda cool, basically you use them to run a callback (generally a lamba) when they go out of scope.
It has a *very minor* performance loss compared to the goto stuff we were doing before, but it makes the code more readable since you wont be skipping declarations of variables and stuff.
=> Add and use ScopeGuard

primedev/client/audio.cpp, primedev/config/profile.cpp, primedev/core/convar/convar.cpp, primedev/core/hooks.cpp, primedev/core/hooks.h, primedev/core/math/bitbuf.h, primedev/core/memory.cpp, primedev/logging/logging.cpp, primedev/masterserver/masterserver.cpp, primedev/mods/autodownload/moddownloader.cpp, primedev/plugins/plugins.cpp, primedev/primelauncher/main.cpp, primedev/scripts/client/scriptserverbrowser.cpp, primedev/scripts/scriptdatatables.cpp, primedev/scripts/scripthttprequesthandler.cpp, primedev/server/auth/bansystem.cpp, primedev/server/auth/serverauthentication.cpp, primedev/shared/exploit_fixes/exploitfixes.cpp, primedev/shared/misccommands.cpp, primedev/squirrel/squirrel.cpp, primedev/squirrel/squirrel.h, primedev/util/printcommands.cpp, primedev/util/printmaps.cpp, primedev/wsockproxy/loader.cpp
[C4267](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4267?view=msvc-170): implicit conversion from `size_t` to a smaller type
If you want to test and make sure i got them, you can compile with `/W4 /we4267` (msvc)
=> Address C4267 compiler warnings

primedev/thirdparty/silver-bun/module.cpp
Closes #678 
Marking as draft until I can get some confirmation of the fix.
=> Fix crash in silver-bun

primedev/server/serverpresence.cpp, primedev/shared/exploit_fixes/exploitfixes.cpp
yeah so when I was resolving conflicts I couldn't really tell what had to remain so some stuff got removed ( resolving conflicts sucks ). Then no one looked at it when merging😅
hopefully now everything is good
=> I reverted things in #680 accidently when resolving conflicts so this is here to fix it

.github/workflows/merge-conflict-auto-label.yml
so that labels can easily be updated if need be.
=> Add option to manually run merge conflict label action

primedev/thirdparty/silver-bun/module.cpp, primedev/thirdparty/silver-bun/module.h, primedev/windows/libsys.cpp
Mostly ported from 368f66043c6b908dc93ec29f3e856beaaabf6df5 with some modifications to the recursion
=> Call module callbacks for nested imported modules (i.e `mileswin64.dll`)

.github/pull_request_template.md
Same as https://github.com/R2Northstar/NorthstarMods/pull/850
=> Add code review and testing sections to pull request template

primedev/thirdparty/silver-bun/module.cpp
Hopefully fixes crash related to #780
draft until verified as fixed
=> Fix module callbacks related crash

.github/labeler.yml, .github/workflows/auto-label-pr.yml
Currently adds "needs code review" and "needs testing" to all PRs made against a branch with this action. See https://github.com/ASpoonPlaysGames/NorthstarLauncher/pull/4 for testing.
=> Add GitHub Action to automatically label PRs

primedev/primelauncher/resources.rc
Fixes the LGBT logo being enabled by default
See https://github.com/R2Northstar/NorthstarLauncher/pull/842#discussion_r2047929975 for reference
=> fix: LGBT logo being enabled by default

primedev/mods/mod.cpp, primedev/mods/mod.h, primedev/mods/modmanager.cpp, primedev/mods/modmanager.h
Aims to simplify the ModManager mod loading logic and improve readability.
=> Improve ModManager logic

primedev/plugins/interfaces/sys/ISys.cpp, primedev/plugins/pluginmanager.cpp, primedev/plugins/pluginmanager.h, primedev/plugins/plugins.cpp, primedev/plugins/plugins.h
=> Finalize reloaded Plugins

primedev/squirrel/squirrel.h, primedev/util/version.cpp
Fixes https://github.com/R2Northstar/NorthstarLauncher/issues/114
=> Replace sprintf usage with sprintf_s in version.cpp

primedev/scripts/scriptdatatables.cpp, primedev/squirrel/squirrel.cpp
Should close #868
Adds some functionality to check and log failed squirrel function hooks, and fixes the currently incorrect ones.
=> Fix broken squirrel function hooks
