- BUILD.md
Maybe this is unnecessary, but adds some instructions for using the Visual Studio Build Tools to compile Northstar.
This allows people to compile the project who don't want to install the full IDE.
> Add VS Build Tools instructions

- Northstar-Legal.txt
- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj
Like https://github.com/R2Northstar/Northstar/pull/101 but for the NorthstarLauncher repo instead
Adds a legal notices file to the root of the repo including all licenses and copyright information for third party libraries utilized by Northstar, along with Northstar's license itself. This file is copied into the build directory when compiling, making it easy to include in future published releases of Northstar.
If I missed anything, and this no longer has coverage of used third party libraries, let me know.
So, why in the NorthstarLauncher then?
* Not fragmented from source
* Being put in the Northstar repo distances it from the activity
* This is where the referenced projects are actually used
* Could lead to neglect if kept elsewhere
* Properly version controlled along with releases
* …
> Add legal notices file to builds

- NorthstarDedicatedTest/miscserverfixes.cpp
Avoids a crash that occurs when quitting the game from the console.
Kind of a hacky workaround, but it seems to work fine.
> NOP out call to VGUI_Shutdown during server DLL shutdown

- NorthstarDedicatedTest/languagehooks.cpp
It's common to remove various Titanfall client-only files on dedicated servers to reduce the install files, including the `r2/sounds` folder. However since v1.4.0 removing the sounds folder results in the dedicated server shutting down while loading with these log lines:
```
[02:30:26] [info] Origin detected language "russian", but we do not have audio f
or it installed, falling back to the next option
[02:30:26] [info] Detected system language: english
[02:30:26] [warning] Caution, audio for this language does NOT exist. You might
want to override your game language with -language command line option.
abnormal program termination
```
This PR avoids hooking `GetGameLanguage` on dedicated servers which seems to fix the issue, I'm guessing this was probably unintentionally left out since …
> Don't hook language functions on dedicated server

- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj
- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj.filters
- NorthstarDedicatedTest/dllmain.cpp
- NorthstarDedicatedTest/latencyflex.cpp
- NorthstarDedicatedTest/latencyflex.h
Adds LatencyFleX, an open source and vendor agnostic input latency reduction technology similar to Nvidia's Reflex. Currently only works on Linux via Wine/Proton, but future versions may support Windows as well. Falls back to doing nothing if LatencyFleX isn't available.
See here for more information:
https://ishitatsuyuki.github.io/post/latencyflex/
> LatencyFleX Implementation

- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj
- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj.filters
- NorthstarDedicatedTest/audio.cpp
- NorthstarDedicatedTest/audio.h
- NorthstarDedicatedTest/audio_asm.asm
- NorthstarDedicatedTest/dllmain.cpp
- NorthstarDedicatedTest/modmanager.cpp
This commit adds audio override functionality.
Audio overrides should be located in the "audio" folder, which should be located inside the mod folder.
Audio override consists of a definition file (JSON) and a folder with override samples.
Override samples must be Stereo 16-bit WAV files and must be at least 1 second in duration.
Definition structure:
- EventId (string or an array of strings): Sound Event ID(s) to override.
- EventIdRegex (string or an array of strings): Sound Event ID(s) regular expressions, if matched the event will be overrided.
- AudioSelectionStrategy ("sequential" or "random"): Selection strategy for multiple override samples.
Additionally, "ns_print_played_sounds" convar has been added to print out sound events as they're requested.
Example mod: …
> Audio Override

- NorthstarDedicatedTest/dedicated.cpp
- NorthstarDedicatedTest/masterserver.cpp
- NorthstarDedicatedTest/masterserver.h
Server name and desc now support UTF-8 chars in Unicode codepoints.
note: you might need to chcp 65001 in bat before using utf-8 charset names to avoid garbage characters
Dedicated servers now display the server name on the CMD title for better identification.
> Various fixes and optimizations on dedi title and server info

- LauncherInjector/main.cpp
- NorthstarDedicatedTest/hooks.cpp
- NorthstarDedicatedTest/languagehooks.cpp
- loader_launcher_proxy/dllmain.cpp
- loader_wsock32_proxy/dllmain.cpp
- loader_wsock32_proxy/loader.cpp
- loader_wsock32_proxy/loader.h
* dedicated server will no longer crash if the whole r2/sound dir is removed rather than just its contents
* EA Desktop-installed game will not throw permission error or require running as administrator anymore, instead it will copy original wsock to a temp dir and continue working
* improved error messaging around wsock32, for example failure to load the copied wsock32 will show an error about it rather than just "initialization routine failed" and a bug around buffer manipulations that broke one of the error messages
* added a detection of DLL load failure in case the failed to load thing is a dependency and not a DLL itself (it really was not obvious from the error message itself if you aren't having a PTSD with WinAPI already)
* improved main function for error messages to detect a …
> Misc improvements

- NorthstarDedicatedTest/playlist.cpp
By removing IsDedicated check it allows to use playlistvaroverrides on servers launched through the game (private match / listen server).
It seems it does not have any other side effects on the client so far.
> make playlist overrides work on private match

- LauncherInjector/main.cpp
- NorthstarDedicatedTest/dedicatedmaterialsystem.cpp
When starting the dedicated server from NorthstarLauncher, always default to loading the d3d11 and gfsdk stubs from `bin/x64_dedi`. If the stubs fail to load or `-nostubs` is specified, the launcher reverts to the old behaviour of using the GPU, or WARP if `-softwared3d11` is specified.
updates #79
> Implement stub loading

- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj
- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj.filters
- NorthstarDedicatedTest/chatcommand.cpp
- NorthstarDedicatedTest/chatcommand.h
- NorthstarDedicatedTest/clientchathooks.cpp
- NorthstarDedicatedTest/clientchathooks.h
- NorthstarDedicatedTest/dllmain.cpp
- NorthstarDedicatedTest/localchatwriter.cpp
- NorthstarDedicatedTest/localchatwriter.h
- NorthstarDedicatedTest/miscserverscript.cpp
- NorthstarDedicatedTest/serverauthentication.cpp
- NorthstarDedicatedTest/serverauthentication.h
- NorthstarDedicatedTest/serverchathooks.cpp
- NorthstarDedicatedTest/serverchathooks.h
- NorthstarDedicatedTest/squirrel.cpp
- NorthstarDedicatedTest/squirrel.h
Mod changes: https://github.com/R2Northstar/NorthstarMods/pull/217
Features:
- Server mods can now send chat messages outside of just intercepting incoming ones: this includes impersonating players, sender-less "announcement"/anonymous style messages, and whisper versions of both.
- The client can intercept incoming chat messages. Client-side chat formatting has been completely replaced by script to open up customisation options.
- Client mods can display custom announcement messages in the local player's chat.
- Anonymous messages all support ANSI escape codes for colours, so servers and mods can do fun things like this:
> Advanced chat: custom messages and client hooks

- NorthstarDedicatedTest/dllmain.cpp
Apparently creating a `fs::recursive_directory_iterator` crashes if the directory does not exist. Oops!
> Fixed crash with plugin loading

- NorthstarDedicatedTest/clientchathooks.cpp
- NorthstarDedicatedTest/localchatwriter.cpp
- NorthstarDedicatedTest/localchatwriter.h
Mostly just moves things around in `CHudChat__AddGameLineHook` to avoid calling `squirrel->setupfunc` in cases where we might not call `squirrel->call`.
Fixes #101
> Fix #101, chat hook memory leak

- BUILD.md
We changed from `r2northstar` to `northstar` a while back which broke the link in the readme.
> Update link to Discord server

- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj
- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj.filters
- NorthstarDedicatedTest/clientruihooks.cpp
- NorthstarDedicatedTest/clientruihooks.h
- NorthstarDedicatedTest/dllmain.cpp
allows rui rendering to be enabled/disabled with the cvar rui_drawEnable (this is something respawn can do on dev builds, with a cvar of the same name)
works fine in testing, haven't encountered any issues with it
> add rui_drawEnable

- NorthstarDedicatedTest/masterserver.cpp
primarily done to prevent users unknowingly leaking sensitive params through their logs
> make curl logging optional

- NorthstarDedicatedTest/ExploitFixes.cpp
- NorthstarDedicatedTest/audio.cpp
Before changing `.clang-format` we should first make sure that code appeals to the current version of `.clang-format`. Hence this PR.
> Fix formatting to stop clang-format failing in CI

- NorthstarDedicatedTest/masterserver.cpp
- NorthstarDedicatedTest/serverauthentication.cpp
Properly initializes AuthData structs where used.
This does not get done automatically in debug mode because c++ is weird like that
> Fix debug builds

- LauncherInjector/resources.rc
- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj
- NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj.filters
- NorthstarDedicatedTest/ns_version.h
- NorthstarDedicatedTest/version.cpp
This way, we don't get the wrong version number when launching Titanfall2.exe via `-northstar`
The hardcoded value should be overwritten by CI on release (https://github.com/R2Northstar/Northstar/pull/262)
Fixes #129
> Hardcode version number

- NorthstarDedicatedTest/serverauthentication.cpp
- NorthstarDedicatedTest/serverauthentication.h
Compare uid that is sent to `CBaseServer::ConnectClient` with the one present during `CBaseClient::ActivatePlayer` and kick if they don't match.
> Compare uid from connect on activate

- NorthstarDedicatedTest/serverauthentication.cpp
probably should've done this earlier, unsure if changes much in practice really but probably just good to do
> dont allow multiple of the same account to connect without a commandline arg

- NorthstarDedicatedTest/dllmain.cpp
- NorthstarDedicatedTest/miscserverfixes.cpp
- NorthstarDedicatedTest/miscserverfixes.h
This is a rewrite of CLZSS::SafeUncompress but with an extra guard to block badly formed LZSS data that attempt to read segments from before the start of the output buffer, sometimes causing a segfault. The added check is lines 88-92, everything else should work identical to vanilla.
> Fix segfault on badly formed compressed packets

- NorthstarDedicatedTest/masterserver.cpp
- NorthstarDedicatedTest/masterserver.h
- NorthstarDedicatedTest/scriptserverbrowser.cpp
Adds this funky little dialog box when failing to authenticate with (master)server
Needs to be updated with localization files for all languages
> Localize error messages from masterserver

- NorthstarDedicatedTest/masterserver.cpp
If gameserver receives DUPLICATE_SERVER response it will retry the auth request after a timeout of 10 seconds.
Retries will stop after 10 attempts.
Uses `GOTO`s to achieve this which is not particularly nice but I assume acceptable as we use the already as well in this part of the code.
For testing I spun a dedicated server, killed it after auth finished, then immediately created a new one. Output shows that it retried after failure until it was able to connect on the 2nd attempt. Then joining the server and playing around with it worked as expected.
> Attempt reconnect in case of DUPLICATE_SERVER

- NorthstarDedicatedTest/serverauthentication.cpp
Setting a default value for _net_chan_limit_msec_per_sec_ will fix the issue of singleplayer games spamming warnings in the console.
> Set default val for net_chan_limit_msec_per_sec

- NorthstarDedicatedTest/serverauthentication.cpp
Write access isn't needed.
pg9182/northstar-dedicated#13
> Open placeholder_playerdata as an input stream

- NorthstarDedicatedTest/latencyflex.cpp
Enhancement of previous PR #168 
Fixes a crash issue experienced in bottles when LatencyFleX fails to load due to an initialization error. Now handled gracefully.
As before, works with the original and modern release of LatencyFleX. Also features better logging than before.
> LatencyFleX Implementation Update

- NorthstarDedicatedTest/bansystem.cpp
I have no proof that this will actually ever cause a real problem, but it's definitely a good idea and is more proper.
> Use strtoull instead of strtoll for uint64s

- NorthstarDedicatedTest/ExploitFixes.cpp
Titanfall 2 has the Portal 2 command-processing system still built in.
This is what leads to the respawn exploit, sound playing exploit, etc.
The sound playing exploit was already fixed in a recent commit (although I despise the complete disregard for following established standards/formatting), my hook is of the same function and fixes other exploitative commands as well.
Sorry guys, no more respawning in front of your killers with a keybind lol. It was fun while it lasted.
> ExploitFixes: Fix respawn exploit and block other Portal 2 commands

- NorthstarDedicatedTest/rpakfilesystem.cpp
- NorthstarDedicatedTest/rpakfilesystem.h
Potentially fixes #201 ? Definitely fixes an issue where every custom rpak was being loaded every time any other rpak was loaded ever, which was preventing us from having more than 1 custom rpak
> fixed custom rpaks being loaded more than once

- NorthstarDedicatedTest/serverauthentication.cpp
This is the native version of https://github.com/R2Northstar/NorthstarMods/pull/391. I re-used the same convar name as in that PR.
Setting `ns_should_log_all_clientcommands` to `1` will enable the logging. By default the value is `0`, i.e. no logging of client commands.
Sample output:
```
[2022-06-25 00:41:32.602] [info] XXXXXXXXX with UID YYYYYYYY sent stringcommand CC_RespawnPlayer Pilot
```
together with a command blocked by exploitfixes:
```
...
[2022-06-25 00:40:01.157] [info] XXXXXXXXX with UID YYYYYYYY sent stringcommand emit 
[2022-06-25 00:40:01.157] [info] [SERVER SCRIPT] ############################
[2022-06-25 00:40:01.157] [info] [SERVER SCRIPT] CommandString: load_recent_checkpoint was not added via AddClientCommandCallback but is being called in CodeCallback_ClientCommand …
```
> Log all clientcommands if `ns_should_log_all_clientcommands` is set

- NorthstarDedicatedTest/squirrel.cpp
- NorthstarDedicatedTest/squirrel.h
Some Command Line Functions are still allowed
To allow functions again use command line parameter `-allowsquirreldevfunctions`
> Block developer squirrel functions

- NorthstarDedicatedTest/ExploitFixes.cpp
- NorthstarDedicatedTest/ExploitFixes.h
- NorthstarDedicatedTest/NSMem.h
- NorthstarDedicatedTest/dllmain.cpp
This depricates/undoes the changes made in https://github.com/R2Northstar/NorthstarLauncher/commit/d961347a611a8f4e670430008f562cdb042ffdd9.
The reason that commit was made is because a particular KHOOK for IsValveMod simply wasn't working at all.
This is because KHooks weren't initialized until server.dll is loaded, and IsValveMod is called only BEFORE this point.
This PR makes all KHooks initialize right after their respective module loads, and fixes this issue.
I also added a spdlog message when the IsValveMod hook is fired, so testing should be super easy 👍
> Fix KHook hooking order to prevent missed hooks

- .github/pull_request_template.md
Adds the following two lines to the template to give hints as to what helps a PR get merged faster.
```
-> For fixes, description on how to reproduce the bug are appreciated and help your PR get merged faster
-> For features, description on how to use the feature is appreciated and will help your PR get merged faster
```
> Mention reproducing bugs and feature usage description in PR template

- NorthstarDedicatedTest/bansystem.cpp
- NorthstarDedicatedTest/bansystem.h
This closes #165. 
In the current state it only works with #227!
When unbanning it comments out the uid and adds a comment with the local time when the person was unbanned. Gives a nice overview i think, but it only works with #227 since that adds the comment functionality.
---
> Fixed `unban` not overwriting `banlist.txt`

- NorthstarDedicatedTest/squirrel.h
The correct type is `uint8_t`, not `uint8` which is non-standard and is Microsoft specific.
The `#define` caused an error for the RCON PR (#100).
The commit in this PR was cherry-picked as 4573d5e3141915f7066f182b47dac6a1d7d7bdcb from #100
> Remove potentially clashing define

- NorthstarDedicatedTest/logging.cpp
> Add log colours because they are pretty

- .git-blame-ignore-revs
Ignore folder rename in git history when checking with `git blame`. When checking the author of a specific line we obviously don't want to show the folder rename commit as that didn't actually change the line.
> Ignore folder rename in git history

- .editorconfig
- .git-blame-ignore-revs
- .github/pull_request_template.md
- .github/workflows/ci.yml
- NorthstarDLL/bansystem.cpp
- NorthstarDLL/bansystem.h
- NorthstarDLL/ns_startup_args.txt
- NorthstarDLL/ns_startup_args_dedi.txt
- NorthstarLauncher/ns_startup_args.txt
- NorthstarLauncher/ns_startup_args_dedi.txt
Adds from main to refactor:
- `.git-blame-ignore-revs` update
- `.editorconfig` add
- hot reload banlist
- PR template
- deleting startup args txt
> Update refactor with some commits from main

- NorthstarDLL/NorthstarDLL.vcxproj.filters
- NorthstarDLL/dedicated.cpp
- NorthstarDLL/masterserver.cpp
- NorthstarDLL/masterserver.h
- NorthstarDLL/misccommands.cpp
- NorthstarDLL/miscserverscript.cpp
- NorthstarDLL/modmanager.cpp
- NorthstarDLL/playlist.cpp
- NorthstarDLL/plugins.cpp
- NorthstarDLL/scriptmainmenupromos.cpp
- NorthstarDLL/scriptserverbrowser.cpp
- NorthstarDLL/serverauthentication.cpp
Part of refactor. I basically took the changes from 037113d4b8032cd3715d879c2f4b08f66fa2be43 and added them onto main, excluding the debug build fix as that was related to a commit on refactor that is not yet present on main.
> Rename some members of MasterServerManager

- NorthstarDLL/logging.cpp
catch an error when log file cannot be created instead of silently crashing, which can happen if the path isn't writable and confuse the user (after the MessageBox is shown, the game will continue launching, as non-writable log file isn't a fatal issue)
[ separated from #272 ]
> Display error if logs path isn't writeable

- NorthstarLauncher/main.cpp
- loader_launcher_proxy/dllmain.cpp
- loader_wsock32_proxy/dllmain.cpp
set current working directory to the exe path -- this is normally expected to be set to that, but under certain circumstances where you create a shortcut to NorthstarLauncher.exe or otherwise use non-direct method of launching it (3rd party game launchers etc), the working directory might have been wrong, causing issues like the log file being attempted to be written in another location, due to use of relative paths
[ separated from #272 ]
> Set current directory properly

- NorthstarDLL/hooks.cpp
This code adds better compatibility with newer controllers and different controller types
Also adds ASLR to the loaded library
> Replace XInput library with updated one

- NorthstarDLL/masterserver.cpp
- NorthstarDLL/masterserver.h
- NorthstarDLL/serverpresence.cpp
- NorthstarDLL/serverpresence.h
This PR also refactors the `MasterServerPresenceReporter` to use `std::async` instead of `std::thread`. This should allow for more thread safety compared to the last solution.
Unable to test on my local machine but it *should* work. I might recommend increasing the max retries to 10 for safety.
Resolves https://github.com/R2Northstar/NorthstarLauncher/pull/171#pullrequestreview-1135289340
> Fix the MS server registration issues.

- NorthstarDLL/clientauthhooks.cpp
A certain someone forgot to put an `0x` in front of their hex number, meaning the offset is wrong. This would cause token to be leaked again.
> Fix token clearing hook

- NorthstarDLL/dedicated.cpp
- NorthstarDLL/misccommands.cpp
removes unnecessary devonly flags from a bunch of cvars and a few commands
this was initially made to add re-remove `cl_updaterate_mp`'s devonly flag, the code for which was removed in refactor (oops), but i decided to go through all the devonly cvars and remove devonly from everything unnecessary
you can still fully strip devonly and hidden from cvars/commands with a commandline flag, but this is mainly for normal use
POSSIBLE CHANGES: 
`cl_footstep_event_max_dist` and `cl_footstep_event_max_dist_titan` control the distance at which footsteps from pilots and titans can be heard, I've made these `FCVAR_CHEAT` (i.e. require `sv_cheats 1`), but maybe they should be made `FCVAR_REPLICATED` instead? (i.e. server controls value, which is then sent to client)
only issue with this is that they …
> Fixup more cvars

- NorthstarDLL/convar.cpp
- NorthstarDLL/misccommands.cpp
idk how this got here tbh, this typo breaks `SetValue( const char* )` because it causes writes to bad memory (usually readonly memory), this fixes that
> fix typo in ConVar::SetValue( const char* )

- NorthstarDLL/r2engine.h
this was assumedly changed by mistake when PERSISTENCE_MAX_SIZED was upated, without modifying padding to next property afterwards
luckily this didn't break any of our code since we still wrote it to each player (just, to the wrong place), but did break anywhere respawn code read uid
> change accidentally broken m_UID offset

- NorthstarDLL/misccommands.cpp
Unsure if this is the proper fix for this but it seems as if the client tries to set this to 0 while in a server and cannot due to it being dev-only. 
We previously had it without the dev-only flag and I don't believe there should be any negative effects due to this. 
Should fix R2Northstar/Northstar#359
> remove dev-only flag from save_enable

- NorthstarDLL/misccommands.cpp
Seems like this command was missed when removing convar flags
> Remove dev only from mat_colorcorrection

- NorthstarDLL/crashhandler.cpp
- NorthstarDLL/crashhandler.h
This PR refactors the crashhandler and adds several new features:
* Support for catching runtime C++ exceptions
* Extended register dump support (segments, RIP, vector registers)
* Adds proper formatting to the error dump
Example of the new error log:
> New crashhandler

- NorthstarDLL/NorthstarDLL.vcxproj
- NorthstarDLL/NorthstarDLL.vcxproj.filters
- NorthstarDLL/filesystem.h
- NorthstarDLL/pch.h
- NorthstarDLL/r2engine.h
- NorthstarDLL/r2server.h
- NorthstarDLL/structs.h
This new file introduces a new syntax for defining structs we have reversed.
This allows us to define fields by their offset, and removes the need for padding fields, making them a lot more maintainable.
> New syntax for reversed structs

- NorthstarDLL/crashhandler.cpp
- NorthstarDLL/crashhandler.h
Turns out that under windows, if you throw a runtime exception and catch it, it still passes through the exception filter. I was not aware of this, and was generating a dump file whenever the exception filter ran, since i assumed we would always be crashing at one point.
> Fix slow keyvalues building

- NorthstarDLL/logging.cpp
I forgot to update this piece of code to make it so that the file sink gets pushed to all loggers instead of only the `[NORTHSTAR]` one
> Fix loggers not sinking to log file

- NorthstarDLL/scriptjson.cpp
This PR simply makes the DecodeJSON() SQ function return `SQRESULT_NOTNULL` as to fix an issue where the Squirrel side would never return the decoded JSON table.
> Fix DecodeJSON() not returning SQRESULT_NOTNULL.

- NorthstarDLL/squirrel.cpp
> Fix script compile errors not being flushed to log file

- NorthstarDLL/squirrel.cpp
Dedicated server should almost never call abort in the event of a crash.
> Exit instead of abort on server compile error

- NorthstarDLL/nsprefix.cpp
Should help with #347 apparently?
Could use testing with docker, but it doesn't set the title for normal dedis anymore.
> Don't set initial dedicated server title to the profile name

- NorthstarDLL/squirrel.cpp
Fixes a bug with UI VM destruction. The functions in question take a `CSquirrelVM*` instead of an `HSquirrelVM*`, which causes `IsUIVM()` always returns false.
> Fix UI VM Destruction

- NorthstarDLL/misccommands.cpp
allows r_drawviewmodel to be set without cheats, this is fine, since people already do similar things with mods anyway, just makes it easier
> remove sv_cheats requirement from r_drawviewmodel

- NorthstarDLL/scriptmodmenu.cpp
This PR makes mod related functions such as `NSGetModVersionByModName()` global, as they previously were only accessible in UI contexts.
Example:
```lua
Spyglass_SayAll(format("Initializing core, version %s.", NSGetModVersionByModName("IMC.Spyglass")));
```
> Make most mod-setting related funcs global.

- NorthstarDLL/squirrel/squirrel.cpp
Git hates me fr.
It decided to roll back this file to a pre-fixed state during restructure PR
> Fix UI VM Destruction (again again)

- NorthstarDLL/scripts/server/miscserverscript.cpp
This PR adds the following function:
```lua
bool function NSDisconnectPlayer(entity player, string reason);
```
This uses the native `CBaseClient__Disconnect()` function to ensure the player is booted from the server, while still giving them a disconnect reason much like the `disconnect` command.
Available on server VM.
> Add NSDisconnectPlayer() function.

- NorthstarDLL/squirrel/squirrel.cpp
This PR simply makes the squirrel manager process all queued messages from native to Squirrel scripts every frame, instead of the previous behaviour which only processed one.
This is going to be needed for my next PR which adds a callback to Squirrel scripts for when the VM is about to be destroyed.
> Process all squirrel messages in the buffer instead of one per frame.

- NorthstarDLL/squirrel/squirrel.cpp
Simply fixes a few missing `break`s in `AsyncCall_External()` leading to weird behaviour.
> Add missing breaks to AsyncCall_External()

- NorthstarDLL/squirrel/squirrel.cpp
- NorthstarDLL/squirrel/squirreldatatypes.h
Now should open the console automatically when UI VM hits a compile error, could still use some work I think, but this now works.
Also fixes a bug in `IsUIVM` which was the cause of the above not working properly to begin with, thanks to @RoyalBlue1 
Also improves logging around compile errors a bit, logging the response (or lack thereof) to the compile 
Users should now see something like this when they boot the game with a UI compile error, as opposed to the blank screen
> Improve response to UI VM compile errors

- NorthstarDLL/server/serverpresence.cpp
Reverts R2Northstar/NorthstarLauncher#386
Current code causes this to be a breaking change for joining players. We need to first adjust current code base to make this non-breaking
> Revert "add FCVAR_REPLICATED to ns_server_name"

- NorthstarDLL/NorthstarDLL.vcxproj
- NorthstarDLL/NorthstarDLL.vcxproj.filters
- NorthstarDLL/scripts/client/clientchathooks.cpp
- NorthstarDLL/server/serverchathooks.cpp
- NorthstarDLL/util/utils.cpp
- NorthstarDLL/util/utils.h
Fixes regressions introduced with #389 (https://github.com/R2Northstar/NorthstarLauncher/pull/389/commits/4df475857755bbc0fddd72c34c0ecbc10db95e90).
Previous implementation could cause crashes due to null pointer dereference and removed all UTF-8 characters.
Current implementation fixes aforementioned null pointer dereference, preserves valid UTF-8 sequences while removing invalid ones (invalid ones won't crash). Furthermore, duplicated code was moved out to a common file.
Also allows `:` as suggested by cpdt analogous to here: https://github.com/R2Northstar/NorthstarLauncher/blob/main/NorthstarDLL/client/localchatwriter.cpp#L414
> Fix issues of restriction of chat message charset

- NorthstarDLL/client/modlocalisation.cpp
Change how we load localisation to fix overriding individual localisation strings being weird.
With the old localisation loading code, our custom value in `Northstar.Custom` for the string `GAMEMODE_FW` wouldn't load, this fixes that by changing where we load our localisation to be more consistent
> Fix overriding individual localisation strings being weird

- NorthstarDLL/core/convar/concommand.cpp
- NorthstarDLL/engine/hoststate.cpp
- NorthstarDLL/engine/r2engine.cpp
- NorthstarDLL/engine/r2engine.h
- NorthstarDLL/shared/exploit_fixes/exploitfixes.cpp
- NorthstarDLL/shared/misccommands.cpp
Allows mods to create a cfg for the initialisation and cleanup of gamemodes, to be run on server before the server initialises. This is mainly to setup engine vars that need to be set before server init (i.e. the network convars required for FW to work correctly)
to use, create a `setup_gamemode_{gamemode}.cfg` and `cleanup_gamemode_{gamemode}.cfg` file in `mod/cfg/server`, and they will be run automatically on server startup/destruction.
Also contains utility commands primarily for these cfgs, mainly `cvar_reset`, that resets a cvar to its default value
> Execute cfgs before server startup for gamemode being run

- NorthstarDLL/util/utils.cpp
So that me and @GeckoEidechse can calmly sleep knowing it was fixed xD
These ifs are mutually exclusive hence the fix (we check for byte 1).
> Pedantic fix for #391 (use if-else instead of if)

- NorthstarDLL/mods/modmanager.cpp
- NorthstarDLL/mods/modmanager.h
This pull request introduces remote mods folder, located at `/runtime/remote/mods`, that will store future auto-installed mods.
In short, it's the *"mods need to pull from 2 folders, local (user-installed) and remote (auto-installed)"* mentioned by @BobTheBob9 in https://github.com/R2Northstar/NorthstarLauncher/issues/396.
* Creates remote mod directory if it does not exist;
* When loading mods, check local folder AND remote mod folder
*(note: there was already a `REMOTE_MOD_FOLDER_SUFFIX` variable in code, I simply added some stuff around to use it)*
> feat: Remote mods directory

- NorthstarDLL/dedicated/dedicated.cpp
`launchplaylist` selects a random map and mode from a given playlist and starts a server on that playlist, this PR allows it to be used as a startup command to set startup map on a dedicated server
> Allow `launchplaylist` to be used to start dedicated servers

- NorthstarDLL/dedicated/dedicated.cpp
- NorthstarDLL/logging/crashhandler.cpp
- NorthstarDLL/logging/logging.cpp
- NorthstarDLL/logging/logging.h
loggers don't seem to flush properly on `abort()`, this flushes them beforehand
> Flush loggers properly on dedicated server shutdown

- NorthstarDLL/core/filesystem/rpakfilesystem.cpp
prevents dedicated server from loading streaming probe files (stbsp) or streamed texture data (starpaks)
> Do not load streaming files on dedicated server

- NorthstarDLL/mods/modmanager.cpp
- NorthstarDLL/mods/modmanager.h
- NorthstarDLL/squirrel/squirrel.cpp
This PR adds a new callback to configure in a mod's `mod.json` file. The `Destroy` callback will be executed right before the VM of the given context is destroyed:
```json
{
"Path": "spyglass/client_globals.nut",
"RunOn": "CLIENT && MP",
"ClientCallback":
{
"After": "Spyglass_ClientGlobalsInit",
"Destroy": "Spyglass_ClientGlobalsDestroy"
}
}
```
```lua
void function Spyglass_ClientGlobalsDestroy()
{
printt("hello i get destroyed oh no")
}
```
The above example would give the following result:
> Add Destroy callback for squirrel scripts.

- NorthstarDLL/scripts/scripthttprequesthandler.cpp
e.g., `error C3861: 'SQ_InternalMakeHttpRequest': identifier not found`
> Fix build errors due to declaration order in scripthttprequesthandler

- NorthstarDLL/squirrel/squirrel.h
one line fix baby!
`callingmodfunc` fails when a file path uses uppercase letters, because `ModManager::NormaliseModFilePath` is not used to convert uppercase letters to lowercase ones.
This is the fix.
das it :)
> me when case inconsistency

- NorthstarDLL/server/auth/serverauthentication.cpp
This is backwards-compatible with old masterserver versions (it will be treated as a general authentication failure).
closes #431 
recommends #433 (client support)
recommends R2Northstar/Atlas#30 (atlas support)
recommends R2Northstar/NorthstarMods#598 (client support)
> Reject banned players during masterserver auth

- .github/workflows/release.yml
On tag creation, this creates a new release and uploads the corresponding compiled launcher and debug files, so that we can just pull the fully compiled binary from [release repo](https://github.com/R2Northstar/Northstar) afterwards instead of having to rebuild it.
This is one puzzle piece in resolving https://github.com/R2Northstar/Northstar/issues/431
For a finished test run of the same code, see
- CI run: https://github.com/GeckoEidechse/Temp-NorthstarLauncher/actions/runs/4374532041
- Uploaded files: https://github.com/GeckoEidechse/Temp-NorthstarLauncher/releases/tag/v0.0.13
> CI create release and upload files on tag

- NorthstarDLL/squirrel/squirrel.cpp
for some reason they were removed in pr #310.
I need `sq_getobject` for some plugins on the ui vm and since they are null, I can't use them.
would close #427 :)
> Bring back sq_getobject and sq_getthisentity for the client and ui vm

- .github/workflows/release.yml
To address a warning currently shown when running the checkout action:
>   Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/download-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Bump download-artifact action to v3

- NorthstarDLL/shared/exploit_fixes/ns_limits.cpp
reverts some changes made by #411 , specifically to do with replacing Plat_FloatTime
Explanation of why this was a problem yoinked from discord
should fix
- https://github.com/R2Northstar/Northstar/issues/448
maybe also fixes
- https://github.com/R2Northstar/Northstar/issues/449 
- https://github.com/R2Northstar/Northstar/issues/450
> Fix stringcmd limits causing unnecessary disconnects

- NorthstarDLL/masterserver/masterserver.cpp
The error.msg field has always been around, but we never used it.
recommends R2Northstar/NorthstarMods#598 (to show it for server auth as well as self auth)
> Use detailed master server error messages when available

- NorthstarDLL/scripts/scriptjson.cpp
Fixes `DecodeJSON` failing to raise a script error if the document has parsing errors.
> Fix DecodeJSON fatalParseErrors param

- NorthstarDLL/mods/modmanager.cpp
Calling a ConCommand added in `mod.json` (introduced in #373) with 0 args raises an error
```
> concommand_test
> SCRIPT ERROR: [UI] wrong number of parameters (calling ConCommandTest): found 2, expected 1
```
where `ConCommandTest()` is a Squrriel function with **0** argument. `command.ArgC()` is 1 when no arg is inputted to console so wrong args are passed to squirrel.
Here's a example of my mod.json.
```json
"ConCommands": [
{
"Name": "concommand_test",
"Function": "ConCommandTest",
"Context": "UI",
"Flags": 0,
"HelpString": "example script concommand"
}
],
```
Tested:
- ConCommand with 0 and 1 arg works fine.
BTW: args passed to squirrel is always a array of string so `command.ArgC()` is always 2 if more than 0 arg is inputted in console. Not the point of this pr but should we change …
> Fix incorrect script ConCommand argc

- NorthstarDLL/core/convar/convar.cpp
The ParseConVarFlagsString function introduced in 64100065b55f79e76542ba689545c60e6fb0dcef (#373) is utterly broken. It only parses the first flag, logs misleading warnings, has an undefined return value in some codepaths, and is somewhat convoluted.
Luckily, this doesn't [appear](https://github.com/search?q=path%3A**%2Fmod.json+ConVars+Flags&type=code) to affect most (if not all) existing mods, as they all seem to be using integer values for Flags, which is taken as-is.
> Fix parsing string ConVar/ConCommand.Flags from `mod.json`

- NorthstarDLL/dllmain.h
Doesn't exist since 450d0b1ed437cf37b4309af952af8904f3f07768 (#343).
> Remove leftover LoadPlugins declaration

- .github/workflows/ci.yml
`set-output` is being deprecated as per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Replace `set-output` in GitHub Actions workflows

- NorthstarDLL/squirrel/squirrel.cpp
fixes the issue described by #456 by adding a check if the mods are actually enabled.
should be checked if there are any side effects from this ( from my testing there doesn't appear to be any )
after installing the pr disable `Northstar.Client` if you crash then the pr doesn't work, script errors will happen (because you disabled a core mod lol)
fixes #456
> Fix initscript issue

- NorthstarDLL/plugins/plugins.cpp
allows plugins to be actually organized/grouped instead of just dumping them into the `plugins` folder
also useful for mod managers
> Support loading plugins from subdirs

- NorthstarDLL/plugins/plugins.cpp
this command arg was removed in plugins v2
basically it prevents plugins from being loaded
a batch file to start northstar with `-noplugins`
[noplugins-test.zip](https://github.com/R2Northstar/NorthstarLauncher/files/11327229/noplugins-test.zip)
can't upload bat files lol
> Restore `-noplugins` command arg

- .github/workflows/release.yml
Currently cmake builds like this:
```
root/
├── NorthstarLauncher.exe
├── Northstar.dll
└── bin/
└── x64_retail/
└── wsock32.dll
```
This PR makes the release gh actions zip into the same structure as normal CI builds. It currently puts all binaries into the root of the zip which is inconsistent with building on push.
> Update release action to match push action

- NorthstarDLL/core/hooks.h
various things passed to MAKEHOOK are not of the correct type (LPVOID/void*) so explicitly cast them to follow Standard C++.
> cast types in MAKEHOOK macro to follow C++ Standard

- NorthstarDLL/util/printmaps.cpp
`const char const*` would be the same as `const char*` because of the location of the star (*)
`const char *const` would be the correct syntax, a constant pointer pointing to constant data.
> Correct syntax for const pointer const

- CMakeSettings.json
Some contributors are having trouble with the game freezing when running Debug binaries. RelWithDebInfo fixes this for some.
> Add RelWithDebInfo configuration

- NorthstarDLL/scripts/scriptdatatables.cpp
- NorthstarDLL/scripts/server/miscserverscript.cpp
- NorthstarDLL/scripts/server/scriptuserinfo.cpp
some calls to `g_pSquirrel` methods depend on what context is and this may change how `<` is interepreted.
Explicitly labeling it as a template makes it clear to the compiler what it is.
> replace dependent names with explicit template definition

- NorthstarLauncher/main.cpp
This changes no functionality but just improves the readability of the control flow of the function. Instead of hiding value behind variable that gets updated, explicitly return early based on value.
These lines have triggered me every time I have read over them so far to the point that I got annoyed enough to change them.
(not tested btw but change should be obvious enough to see that the resulting logic is the same)
> Improve `ShouldLoadNorthstar()` logic readability

- NorthstarDLL/mods/modmanager.cpp
- NorthstarDLL/mods/modmanager.h
This PR allows for loading Thunderstore mods directly from a separate directory (called `thunderstore-mods` rn, I'm happy to change).
It expects a folder that represents the unpacked zip from the mod from Thunderstore. This heavily simplifies mod management as now there's a direct link between Thunderstore mod and Northstar (Thunderstore folder name).
Loading user installed Northstar mods from `R2Northstar/mods/` is still supported for now as mod-managers need to be updated first and as a fallback for mods not on Thunderstore.
Mod-managers could then also take care of moving existing Thunderstore mods from `mods/` to `thunderstore-mods/`
I will take care of notifying mod-manager authors once a decision about merging (or not merging) this PR has been made.
This PR is an initial …
> Add support for loading Thunderstore mods natively

- NorthstarDLL/dllmain.cpp
- NorthstarDLL/logging/logging.cpp
- NorthstarDLL/logging/logging.h
Relevant log on Fedora 38 running NorthstarProton 8.1
```
[15:16:48] [NORTHSTAR] [info] NorthstarLauncher version: 0.0.0.1+dev
[15:16:48] [NORTHSTAR] [info] Command line: "Z:\home\sentry\.local\share\Steam\steamapps\common\Titanfall2\Titanfall2.exe"   -northstar --use-gl=osmesa
[15:16:48] [NORTHSTAR] [info] Using profile: R2Northstar
[15:16:48] [NORTHSTAR] [info] Operating System: Linux (Wine)
[15:16:48] [NORTHSTAR] [info] Wine build: wine-8.1.r0.gdde73435 ( TkG Staging Esync Fsync )
[15:16:48] [NORTHSTAR] [info] Proton build: NorthstarProton-8.1-1
```
> Add OS, Wine and Proton logging

- NorthstarDLL/plugins/plugins.cpp
closes #509
reposition things a bit, adds a few more sanity checks and looks for dlls in packages.
Tested with the kyurid plugin.
> Add support for loading plugins from Thunderstore packages

- NorthstarDLL/plugins/plugins.cpp
Fixes a crash introduced in #513 which occured when no `<Profile>/packages` dir was present
fs::create_directories doesnt throw when the dir already exists so its safe calling this in both PluginManager and ModManager
> Make sure `packages` dir exists when loading plugins

- NorthstarDLL/dedicated/dedicatedlogtoclient.cpp
- NorthstarDLL/mods/modsavefiles.cpp
- NorthstarDLL/pch.cpp
- NorthstarDLL/plugins/pluginbackend.cpp
- NorthstarDLL/plugins/pluginbackend.h
- NorthstarDLL/scripts/scriptjson.h
- NorthstarDLL/shared/gamepresence.cpp
- NorthstarDLL/shared/gamepresence.h
- loader_wsock32_proxy/CMakeLists.txt
- loader_wsock32_proxy/dllmain.cpp
- loader_wsock32_proxy/loader.cpp
- loader_wsock32_proxy/pch.cpp
With the move to cmake there is no need for the `pch.cpp` files as it generates them automatically.
Also removes leftover `#include "pch.h"` occurrences
> Remove `pch.cpp` and all `#include "pch.h"` occurrences 

- NorthstarDLL/mods/modmanager.cpp
- NorthstarDLL/plugins/plugins.cpp
Closes #524
Added the package pattern to validate if the package is actually valid, copied the code structure from `modmanager.cpp` so its easier to catch anything misbehaving.
> Validate package pattern before checking for plugins

- loader_wsock32_proxy/loader.cpp
The wsock32 proxy didn't support loading Northstar.dll from a profile, for some reason.
This PR copies the function from NorthstarLauncher, which prior for #451 had the exact same code.
> Support DLLs in Profile from wsock32 proxy

- NorthstarDLL/mods/modmanager.cpp
Implements https://github.com/R2Northstar/NorthstarLauncher/pull/503 for remote mods (*i.e.* mods located in the `%profile%/runtime/remote/mods` directory), expecting them to be named after the `AUTHOR-MOD-VERSION` pattern.
Put mods respecting the Thunderstore format in the remote mods directory, and they should be loaded and usable just like mods located in the `packages` directory.
> feat: Enforce Thunderstore format for remote mods

- NorthstarDLL/squirrel/squirrel.cpp
Fixes typo in a offset we hook
**Testing:**
For testing git clone https://github.com/F1F7Y/ServerUtilities and checkout the `fsu3` branch. Then go to lobby ( or activate the server however you want )
On current main you'll script error because the initscript wasn't compiled because the hook is wrong. On this branch you won't script error.
> Fix `CSquirrelVM::Init` hook in `server.dll`

- .github/workflows/release.yml
- NorthstarDLL/CMakeLists.txt
- NorthstarDLL/resource1.h
- NorthstarDLL/resources.rc
closes #455 
will conflict with #541 as the workflow that #541 edits will need the same change added to it
> Export Northstar version number in DLL

- NorthstarDLL/logging/loghooks.cpp
Closes [#506](https://github.com/R2Northstar/Northstar/issues/506)
Would like to add a launch arg in the future ( smth like `-nsdev` ) that would enable all log funcs and other features.
This log call can sometimes slow the game down
> Set `spewlog_enable` default value to 0

- NorthstarDLL/core/filesystem/filesystem.h
- NorthstarDLL/util/printmaps.cpp
adds safeguard to the map command that prevents it from executing if the map is invalid.
I wanted to implement this originally as a plugin but I think it might be quite useful for everyone.
> Add a safeguard to map command

- NorthstarDLL/client/rejectconnectionfixes.cpp
Closes #552 
Basically we were running a string format and then passing the string to the original function, which would then try and format it again (and get bad args). By passing `"%s"` and then our formatted string we basically just protect the vanilla string format
> Fix crash when running `disconnect %%s`

- NorthstarDLL/server/auth/bansystem.cpp
closes #163
The local player (host) should be exempt from the banlist. Note that this doesn't remove the local player through the banlist, it simply doesn't check if they are banned or not
> Always allow the local player through the banlist

- NorthstarDLL/core/tier0.cpp
The standard does not guarantee that `g_pMemAllocSingleton` will default to a falsey value, which our `*alloc` implementations demands.
I believe this change is so small and contained that its not worth testing, can you agree with that @GeckoEidechse ?
> Give `g_pMemAllocSingleton` a default value

- .editorconfig
Setting indent size in `.editorconfig` means that things like GitHub web preview will default to showing tab indent size as 4 spaces.
By default GitHub uses tabsize 8 for indentation making diffs look weird (cause `clang-format` is doing wrong things)
See also https://stackoverflow.com/questions/8833953/how-to-change-tab-size-on-github
> Define indent size in editorconfig

- NorthstarDLL/logging/logging.cpp
Suggestion from #560 
This PR adds dates to logs in the same format which the file name uses. 
Closes #560
> Write date to logs

- NorthstarDLL/core/convar/concommand.h
- NorthstarDLL/core/hooks.h
- NorthstarDLL/shared/maxplayers.cpp
- NorthstarDLL/squirrel/squirrel.cpp
Removes `C4229 "anachronism used: modifiers on data are ignored"` warnings
Reduces warning count from 82 to 6
Literally just play the game for a bit, load some mods, see if you notice any new crashes?
> Reduce warnings due to calling conventions

- NorthstarDLL/client/audio.cpp
Adds a convar to toggle whether we should log from the miles log func
Most of these warnings are warnings about events being starved, in some cases slowing down the game due to the number of log calls.
Closes [#509](https://github.com/R2Northstar/Northstar/issues/509)
> Add `mileslog_enable` convar

- cmake/utils.cmake
The file had mixed indentation (spaces and tabs) when really it should've been spaces only from the beginning
I noticed the indentation change in #569 and spliced it out to make the diff of #569 proper on merge.
No testing needed as this only performs a whitespace change in `utils.cmake`. Check the diff with whitespace changes hidden to verify for yourself :P
> Fixed mixed indentation in utils.cmake

- README.md
Make link to `BUILD.md` relative to `README.md` instead of a hardcoded link to relevant GitHub page
No testing needed as it only modifies `README.md`.
> Make link to BUILD.md relative to README.md

- cmake/utils.cmake
the contents of the submodules were incorrectly counted resulting in a git submodule update on every cmake invocation
This can be easily seen by checking out a different commit in a dependency and trying to build NS with it.
> Correct submodule detection

- .github/workflows/add-to-project.yml
PRs from forks are triggered from that fork which means that they don't have access to the necessary token causing them to fail for the first commit.
> Only run `add-to-project` action on issues

- NorthstarDLL/dllmain.cpp
- NorthstarDLL/plugins/pluginbackend.cpp
- NorthstarDLL/plugins/pluginbackend.h
- NorthstarDLL/plugins/plugins.cpp
Plugin state requires this to be initialised even if `-noplugins` is passed, but if `-noplugins` is passed, it doesn't get initialised.
Moving this to `dllmain` guarantees that it is initialised properly and prevents #580 
closes #580
> Move plugin communication handler init out of plugin manager init

- NorthstarDLL/util/printmaps.cpp
Adds a fix so that #564 can be re-merged
1. Rename r2/maps  
2. Run `maps *` in the console 
If the game does not die, :tada:. 
It should just print the maps found from the vpks.
> Add check for r2/maps folder

- NorthstarDLL/logging/logging.cpp
fixes #533 
Also adds some comments to explain what is going on and puts values into variables instead of using the return value directly.
Yes I used auto, sue me.
> Fix proton detection output

- .github/workflows/ci.yml
- NorthstarDLL/util/version.cpp
closes #369
example of working CI:
https://github.com/ASpoonPlaysGames/NorthstarLauncher/actions/runs/6076234977
> Use 4th digit in version number for CI build number

- NorthstarDLL/client/debugoverlay.cpp
closes https://github.com/R2Northstar/NorthstarMods/issues/689
This code is probably bad idk dude this is weird stuff. Would be cool to get someone better at cpp than me to review this
> Refactor `debugoverlay.cpp` (fix smart pistol lines)

- .gitmodules
- NorthstarDLL/CMakeLists.txt
- NorthstarDLL/mods/autodownload/moddownloader.cpp
- NorthstarDLL/mods/autodownload/moddownloader.h
- NorthstarDLL/mods/modmanager.cpp
- cmake/Findminizip.cmake
This branch allows client to download a mod archive from the Thunderstore API, and extract included mods in the remote mods folder of the current game profile.
Not all mods can be automatically downloaded, as it would cause *some* security issues, and Thunderstore mod name cannot be deduced from actual mod name: to be eligible to auto-downloading, a mod must appear in the list of verified mods.
Said list and complete mod verification procedure are described here: https://github.com/R2Northstar/VerifiedMods
This branch exposes two commands to test the feature:
* `fetch_verified_mods` retrieves verified mods list from the GitHub organization, and stores it locally;
* `download_mod` does the actual mod downloading/extraction job.
* Downloading a mod archive
* Extracting said archive to mods …
> Inital native code for verified mod auto-downloading

- NorthstarDLL/util/printcommands.cpp
Adds various concommands such as 
- `convar_findByFlags`
- `convar_list`
- `convar_differences`
- `convar_find`
The first 3 listed above are already registered as concommands natively but didn't seem to do anything when tested.
`convar_findByFlags` and `convar_find` were already implemented by Bob under the names `findflags` and `find` respectively but the names have been changed to reflect already existing convars. 
All outputs into the console are also alphabetically sorted.
> Convar print commands

- NorthstarDLL/plugins/plugins.cpp
The related line expected 3 args but only 2 args are passed.
Blocks:
- #472 
The change should be obvious and not need testing. If you still wanna though. Simply replace the current DiscordRPC plugin we ship with the v1 version (grab from a release pre `v1.13`).
Before this PR you'll see something along the lines of "LOG ERROR" in your console output where plugin load happens.
With this PR it should log the error just fine.
> Plugin related log error expecting more args

- NorthstarDLL/mods/autodownload/moddownloader.h
File was moved with https://github.com/R2Northstar/VerifiedMods/pull/8
Updates a string const and a comment (2 lines total)
**Testing:**
Simply run `fetch_verified_mods` and `download_mod Fifty.mp_frostbite 0.0.1` and it should work again compared to current main.
> Update link for verified mods JSON file

- NorthstarDLL/mods/modmanager.cpp
I'm aware of the logging rewrite that is currently open, but that doesn't seem to be entirely active currently and this is something that would be helpful when trying to help users
I'm unsure if the code could be implemented more efficiently, I just followed what was done with the mod name for the mod version and it worked in testing
The version number in the package folder does slightly remedy this, but there are still people that install to `mods`, and I don't see this as hurting anything
A log showing this (enabled and disabled):
Enabled mod:
Disabled mod:
> Add mod versions when logging that a mod has loaded

- NorthstarDLL/core/hooks.cpp
The previous logic compared the whole argument, which may be a path, to a string literal.
This checks if the argument ends with the string literal instead.
> Improve replacing `xinput1_3` with `xinput9_1`

- NorthstarDLL/CMakeLists.txt
- NorthstarDLL/audio_asm.asm
- NorthstarDLL/client/audio.cpp
Takes the previous audio event code, which relied on reading out a register using masm, and replaces it with a new hook.
Adapted from NorthstarPrime https://github.com/F1F7Y/NorthstarPrime
> Replace audio event fetching with hook

- NorthstarDLL/server/auth/serverauthentication.cpp
- NorthstarDLL/server/auth/serverauthentication.h
This reverts commit 17217a39681c7fed35bee95195bdba7eaf508911 (PR #548) which introduced a regression allowing auth to progress further than intended.
> Revert "Move player auth to `CServer::ConnectClient` (#548)"

- cmake/Findminizip.cmake
Doing this because I ran into the following error while compiling with msvc-wine
```
z:/home/sentry/git/NorthstarLauncher/thirdparty/minizip/mz_strm_zstd.c(17): fatal error C1083: Cannot open include file: 'zstd.h': No such file or directory
```
What is actually needed from minizip?
This was likely not an issue on windows because of `MZ_FETCH_LIBS`. Should we turn that off to ensure no extra dependencies get in without our knowledge?
> Disable more compression methods for minizip

- NorthstarDLL/client/clientauthhooks.cpp
- NorthstarDLL/core/vanilla.h
- NorthstarDLL/dllmain.cpp
- NorthstarDLL/masterserver/masterserver.cpp
- NorthstarDLL/shared/exploit_fixes/exploitfixes.cpp
- NorthstarDLL/squirrel/squirrel.cpp
- NorthstarLauncher/main.cpp
Old `-vanilla` behaviour is now handled by `-nonorthstardll`
`VANILLA` is exposed as a squirrel constant, set to true when in vanilla compatibility mode.
Differences when in vanilla compatibility mode:
- Doesn't restrict server commands (same as `-norestrictservercommands`)
- Doesn't block FairFight screenshot functions 
- Doesn't do Atlas-related stuff (except for mainmenupromos)
With this PR various script changes will still be needed for proper vanilla compatibility, but it's a good start.
closes #588
> Rework `-vanilla` to be a vanilla compatibility mode

- .github/workflows/merge-conflict-auto-label.yml
Adds a GitHub Action that auto-adds a label to a PR in case there are merge conflicts.
Action in use is https://github.com/marketplace/actions/auto-label-merge-conflicts
I'm not sure if the label also gets auto-removed again but I guess we'll find out :P
> Add Action to add label to PR on merge conflict

- .github/workflows/merge-conflict-auto-label.yml
Runs at 4:20 UTC every day
It was taking a while for labels to get removed, sometimes
> Schedule the merge conflict labelling to run daily

- primedev/client/debugoverlay.cpp
Basically when i integrated some debug overlay stuff from `primedev`, I mistakenly called the original version of the hooked function, instead of the new version. The reason for this was because `primedev` doesn't use `AUTOHOOK`, but we do, and the name of the new function on `primedev` is the same as the original function on main. fun.
Offending commit (i think) https://github.com/R2Northstar/NorthstarLauncher/commit/6e32a584804158daec2f57cfe3fa058f1ce3d0a7
> Fix debug overlay not rendering script function stuff

- primedev/cmake/Findminizip.cmake
Fixes builds failing due to https://github.com/madler/zlib/commit/2e3d86c4e12c4c23db4229eea7d0c1cd4571273e
> Pull zlib from custom fork

- primedev/mods/modmanager.cpp
yeah...
im not adding "needs testing" because uhhh, good luck testing this
> Remove unused variable in mod concommands

- primedev/util/utils.h
`std::function` introduces a layer of indirection that can be removed through templating the class.
> ScopeGuard improvements

- primedev/mods/autodownload/moddownloader.h
The default branch for the VerifiedMods repo was renamed from `master` to `main`. See https://github.com/R2Northstar/VerifiedMods/issues/28 for more info.
**Testing:**
Simply enable MAD by setting `allow_mod_auto_download` to `1` and join any server that requires some verified mod.
> Update default mods list URL

- primedev/CMakeLists.txt
- primedev/wsockproxy/CMakeLists.txt
- primedev/wsockproxy/dllmain.cpp
- primedev/wsockproxy/loader.cpp
- primedev/wsockproxy/wsock32.asm
- moves `WSockProxy` to `wsockproxy/CmakeLists`
- remove exepath stuff from dllmain
+ its still done in loader.cpp because its used when reporting failure
- Disabled any Thread Library calls
+ we don't need to know about threads at all in the proxy
- yoink `wsock32.asm` into outer space
+ turns out, we can just call the function in a void shim since that wont touch the registers
- stop copying `wsock32.dll` to the game directory
+ this should improve the state of things when using the EA App
> Clean up wsock proxy code and move wsock build system logic

- primedev/squirrel/squirrel.cpp
everything was seemingly working before but the offset for the server's `sq_getfunction` is still wrong by a bit and the client one was being set twice for some reason.
[prime dev reference](https://github.com/F1F7Y/NorthstarPrime/blob/e49d88f785372edf0821ed938b93dd28b6e36a9e/primedev/vscript/languages/squirrel_re/squirrel/sqapi.cpp#L491)
> Fix bad offsets of `sq_getfunction`

- primedev/util/printmaps.cpp
The map command should only take one argument, so any more than that is superfluous.
> Don't allow too many arguments to be sent to the map command

- primedev/core/convar/convar.cpp
- primedev/dedicated/dedicated.cpp
- primedev/dedicated/dedicatedlogtoclient.cpp
- primedev/dllmain.cpp
- primedev/logging/logging.cpp
- primedev/logging/logging.h
- primedev/logging/loghooks.cpp
- primedev/logging/sourceconsole.cpp
- primedev/masterserver/masterserver.cpp
- primedev/mods/autodownload/moddownloader.cpp
- primedev/mods/modmanager.cpp
- primedev/pch.h
- primedev/scripts/client/scriptmainmenupromos.cpp
- primedev/scripts/client/scriptmodmenu.cpp
- primedev/scripts/client/scriptserverbrowser.cpp
- primedev/scripts/scriptdatatables.cpp
- primedev/server/auth/bansystem.cpp
- primedev/server/auth/serverauthentication.cpp
- primedev/server/serverpresence.cpp
- primedev/server/serverpresence.h
- primedev/shared/exploit_fixes/exploitfixes.cpp
- primedev/shared/exploit_fixes/exploitfixes_lzss.cpp
- primedev/shared/exploit_fixes/ns_limits.cpp
- primedev/shared/misccommands.cpp
- primedev/squirrel/squirrel.cpp
- primedev/util/printcommands.cpp
Uses a macro to avoid the warning. I could have gone for just commenting out the parameter name in most cases, but for things like `ADD_SQFUNC` the parameter names aren't available as they are part of the macro.
> Address C4100 compiler warnings (unused var)

- BUILD.md
Add instructions to build NorthstarLauncher with [`podman`](https://podman.io/) (rootless Docker alternative) on Linux when using an SELinux enabled distros.
```
$ podman run --rm -it -e CC=cl -e CXX=cl --mount type=bind,source="$(pwd)",destination=/build,Z northstar-build-fedora cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Windows -G "Ninja"
-- NS: Building to /build/game
CMake Deprecation Warning at primedev/thirdparty/minhook/CMakeLists.txt:27 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
-- curl version=[7.81.0-DEV]
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY …
```
> Add instructions to build with podman

- primedev/plugins/plugins.cpp
string members were instances with the char* value before they were sanity checked for NULL.
`std::string(NULL)` is UB, but usually just results in a crash.
@uniboi because he is the author of plugins v4
> Fix plugin with NULL strings causing UB

- primedev/client/languagehooks.cpp
During my debugging around user's game constantly crashes on startup with file corruption detected, I found this code which does not satisfy the guarding logic and need further detection to guard against files named `general_stream_xxx.mstr`. After applying this code change in my NorthstarCN fork, the crashes are resolved.
The initial debugging procedures:
1. Console logs `Origin detected language "stream", but we do not have audio for it installed, falling back to the next option`
2. Games crashes with engine error: file corruption detected.
3. Found problematic code, applied the code change.
4. The problem is fixed without modifying the environment.
> Fix engine error crash caused by language detection hooks

- primedev/plugins/plugins.cpp
Before this change `m_pCreateInterface` was never assigned and thus undefined (and on wine Null initialized) so `Plugin::isValid` would always fail.
> Assign `CreateInterface` member instead of creating a new variable

- primedev/wsockproxy/wsock32.def
Newer versions of lld check for duplicate export and error accordingly
```
lld-link: error: duplicate export ordinal: select
```
> Remove duplicate wsock32 export

- primedev/core/hooks.cpp
- primedev/core/hooks.h
MinHook doesn't check this either so it would also be found out when a Winapi function fails.
Lets fail earlier with an error message.
> Check if hook target is non `null` before calling MinHook

- primedev/client/latencyflex.cpp
some compilers (most notably clang) gets a bit worried that we may be assigning unintentionally.
Using double brackets silences it and lets it know that this is correct.
> Use double brackets to let compiler know assignment is intentional

- primedev/mods/modmanager.cpp
logs errors so we can catch them if they do ever happen.
follow-up to #712
> Add default case for SquirrelContext switch

- primedev/squirrel/squirrel.cpp
In C++ explicit template instantiations need to be done AFTER template declarations are made.
Does not work:
```
template class SquirrelManager<ScriptContext::SERVER>;
template <ScriptContext context> class SquirrelManager;
```
Works:
```
template <ScriptContext context> class SquirrelManager;
template class SquirrelManager<ScriptContext::SERVER>;
```
> Don't instantiate templates before declaration, add missing instantiation

- .github/workflows/ci.yml
THIS ONLY APPLIES TO THE CI, NOT RELEASES
Builds Northstar with the Microsoft provided clang-cl build.
Anything that downloads GH Actions artifacts like FlightCore (@GeckoEidechse) will need to be updated.
Alternative I could check for a way of only having a `LLVM` suffix for clang builds.
> Add clang CI

- .github/workflows/ci.yml
v3 is outdated and will soon be deprecated
Spliced from #722
> Update `actions/upload-artifact` to v4

- primedev/scripts/scriptjson.cpp
Add missing cases for switch cases.
RapidJSON switch gets a new case for null, where we do nothing. Future enum values would result in a new warning. (Might be good to add default case with error logging too?)
> Add missing case for switch cases in JSON deserialization function

- primedev/Launcher.cmake
- primedev/Northstar.cmake
- primedev/wsockproxy/CMakeLists.txt
Microsoft, in their infinite wisdom, decided to suffix some libraries with `.Lib` instead of `.lib` This causes issues with cmake on Linux because it only looks for `.lib` which it won't be able to resolve because the file system is case sensitive. Microsoft does this for backwards compatibility, in cmake this is a limitation so the best solution is to bite the bullet and lowercase all libraries which setups such as wine-msvc and xwin already do.
> Lowercase all linked libraries for building on Linux

- primedev/shared/keyvalues.cpp
The standard states that this must always be a valid pointer so these checks are optimized out anyway. Sane compilers, such as clang, also complain about this and state that this is pointless.
> Remove useless `this` pointer check

- primedev/dedicated/dedicatedlogtoclient.h
- primedev/logging/sourceconsole.h
the compiler knows we want to override here, since the original `custom_sink_it_` is virtual but we should be explicit to prevent any mistakes.
> Add overrides to `custom_sink_it_` methods

- CMakeLists.txt
We tried this already for when MSVC broke Northstar before but didn't merge it since it didn't fix the issue.
I think its best if we use the static runtime anyways to remove more dynamic dependencies that we can't anticipate.
> Use static MSVC Runtime Library

- primedev/core/memalloc.cpp
- primedev/core/memalloc.h
#718 stopped Northstar from working for two reasons:
- the way the *alloc family was declared was not compatible with how the CRT worked
- _recalloc_base was declared but never defined
Microsofts documentation on _recalloc is a bit bad so I followed the chromium implementation
https://chromium.googlesource.com/chromium/src/+/84db13d2045c3bc2753c4048ec1816373de0c3cc/base/allocator/allocator_shim_override_ucrt_symbols_win.h#102
If the chromium implementation is right and only the new bits are zeroed then the r5sdk implementation is wrong.
Since we need to get the old size for recalloc I also implemented _msize
Tested this myself on Windows but I would love to get another tester for this
> Fix memalloc problems

- primedev/CMakeLists.txt
- primedev/primelauncher/CMakeLists.txt
- moves the primelauncher cmake logic into its subdirectory allowing everything related to it to be self contained
> Restructure primelauncher cmake logic

- primedev/thirdparty/rapidjson/document.h
pulls in https://github.com/Tencent/rapidjson/pull/719
resolves https://github.com/Tencent/rapidjson/issues/2277
Its  worth noting that the fix existed since 2016 and had not been pulled in yet.
Worth considering for #715
> Fix const-qualified assignment in RapidJSON

- primedev/mods/modmanager.cpp
`HasMember` asserts `IsObject()` internally.
In release builds this is not an issue but this does not work on Debug builds.
`m_bHasEnabledModsCfg` is the output of `m_EnabledModsCfg.IsObject()` and this pattern exists in other places, so I think this is a "good enough" solution at the moment (though I consider this file to smell a bit)
> Add missing object check in mod manager

- primedev/logging/logging.cpp
gets rid of that annoying
`[*] Failed to create a console window, maybe a console already exists?`
when launching via NorthstarLauncher.exe
> Check for Console Window before allocating one

- primedev/pch.h
- primedev/plugins/interfaces/interface.h
its used once and does not warrant being in the precompiled header
> Remove EXPORT macro from precompiled header

- primedev/pch.h
> Remove unused typedefs from precompiled header

- primedev/mods/autodownload/moddownloader.cpp
Currently, if something bad happens during MAD manifesto parsing (if its format was updated, *for instance*), the game crashes.
Using an unknown MAD manifesto:
`.\NorthstarLauncher.exe -customverifiedurl=https://raw.githubusercontent.com/R2Northstar/VerifiedMods/refactor/include-mod-source-in-version-links/verified-mods.json`:
1. should crash with `main`;
2. should output a warning message with this branch.
> fix: Do not crash on unknown MAD manifesto format

- primedev/squirrel/squirrel.h
`pushSQObject` does not exist. Spliced from #692 as per https://github.com/R2Northstar/NorthstarLauncher/pull/692#discussion_r1591169750
> Fix typo in class member function

- primedev/client/audio.cpp
- primedev/client/audio.h
- primedev/client/languagehooks.cpp
- primedev/core/hooks.cpp
- primedev/mods/autodownload/moddownloader.h
- primedev/mods/modmanager.h
- primedev/plugins/pluginmanager.cpp
- primedev/plugins/pluginmanager.h
- primedev/server/buildainfile.cpp
- primedev/squirrel/squirrel.h
Define `fs` alias for filesystem namespace in source file where used instead of relying on implicit includes.
Spliced from #732
> Define `fs` alias in source file where used

- primedev/logging/logging.cpp
closes #752
reverts #741 and removes the log line since it was originally just added as a precaution
> Fix logging sometimes not working

- primedev/mods/autodownload/moddownloader.cpp
- primedev/mods/autodownload/moddownloader.h
Previously, the verified mods manifesto was fetched on game start without checking if the verified mod feature is enabled Squirrel
-side; with this, the manifesto is only fetched when the user wants to download a mod (meaning they enabled the feature beforehand).
**(must be merged with the mods PR!)**
* Expose `FetchModsListFromAPI` method to Squirrel VM
* Do not invoke `FetchModsListFromAPI` method on client start
* Add `ModInstallState.MANIFESTO_FETCHING` enum value to better track mod install progress
*Without PRs:*
1. Launch game;
2. Check the logs: they should display verified mods manifesto was fetched close to game launch;
*With PRs:*
1. Install both launcher and mods PRs;
2. Launch game, reach MP lobby and enable MAD (`allow_mod_auto_download 1`);
3. Try and connect to a server …
> Only fetch MAD manifesto on server join

- .github/workflows/merge-conflict-auto-label.yml
Just adds a comment to CI file explaining the reasoning for choosing a specific time for the cron job.
> Add comment explaining time choice for cron job

- primedev/mods/modmanager.cpp
Hello frens!
This pr fixes issue #690 
To reproduce the crash on a version without the fix:
1. make a mod with a paks folder
2. put atleast an rpak into it
3. dont make the rpaks.json or make it empty
4. launch the game
this should now crash at line 878 in modmanager.cpp as the original logic tries to set a postload string even tho none exists as the variable bUseRpakJson is being inverted in the if statement and doest ask for an && wether the other statements are also true, thus leading to the string being set to a value that doesnt exist making launcher go brrrt
To Test wether it works:
follow the reproduce steps, and notice that it wont crash and still load rpaks properly.
> Fix postload crash from missing `rpak.json`

- primedev/windows/libsys.cpp
XInput 9.1.0 has [some limitations to do with `XInputGetCapabilities`](https://learn.microsoft.com/en-us/windows/win32/xinput/xinput-versions) that may make the game behave differently when we use it as a replacement for XInput 1.3
XInput 1.4 doesn't have this issue, which means that if it works correctly we should always prioritise using this version over 9.1.0
XInputGetCapabilities is called by the game in at least two places: `inputsystem.dll + 0xCE4C` & `inputsystem.dll + 0xE2DF` (function pointer set at `inputsystem.dll + 0xCF0B`)
I have checked and 1.4 does have the `/DYNAMICBASE` option enabled so it supports ASLR just like 9.1.0.
Since `XInput1_4.dll` is only included stock on Windows 8 and newer, this PR makes it fall back to `XInput9_1_0.dll` if the former couldn't be loaded, as …
> Try loading XInput 1.4 before trying to load 9.1.0

- .clang-format
I'm losing my mind at clang-format making all my short getters and setters into 4 lines for no good reason
> Formatting: Set short inline functions to be on one line

- primedev/Northstar.cmake
- primedev/engine/gl_matsysiface.cpp
- primedev/materialsystem/cmaterialglue.h
- primedev/materialsystem/cshaderglue.h
Reimplements the `mat_crosshair_printmaterial` concommand. As my poor i3 thinkpad with fedora cant run Titanfall 2 nor visual studio i didnt test this branch. It did however work flawlessly on primedev. 
Hop in a map and run the command.
> engine: Restore `mat_crosshair_printmaterial` concommand

- primedev/core/hooks.cpp
- primedev/core/hooks.h
They weren't storing the null terminator since `strlen` doesn't include it. This meant that any `ManualHook`s were logging their name blindly and just reading random memory until they hit a null terminator.
I also moved over to just using `std::string` instead of doing manual allocations etc. since we are doing C++ here we have these tools why not use them.
1. Launch the game without the PR and observe `OnCommandSubmittedHook` doesn't log it's own name properly when enabled (there are also others)
2. Launch the game with this PR and observe that this is now fixed.
> Fix manual hooks storing their name badly

- .clang-format
> Format constructor initializers in a better way

- primedev/core/hooks.cpp
Removes unused `CModule` var. CModule crashes when you give it a dll tha's been loaded as one of these: `LOAD_LIBRARY_AS_DATAFILE`, `LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE`, `LOAD_LIBRARY_AS_IMAGE_RESOURCE`. We have guards for this in libsys but not here.
Idk if this'll fix the issue discussed on Discord but well see
> core: Remove unused `CModule` variable

- primedev/client/clientauthhooks.cpp
- Make sure that authing with Atlas (`AuthenticateOriginWithMasterServer`) still works and all that
> Remove uses of Autohook from `clientauthhooks.cpp`

- primedev/client/clientruihooks.cpp
- Test that `rui_drawEnable` still functions properly (`0` stops drawing all RUI, `1` draw RUI as per usual)
> Remove uses of Autohook from `clientruihooks.cpp`

- README.md
- STANDARDS.md
Adds documentation explaining the coding standards to follow.
Taken from #772 and adjusted slightly based on the context of the PR.
> Document coding standards

- primedev/client/debugoverlay.cpp
- Make sure that `enable_debug_overlays` still works
> Remove uses of Autohook from `debugoverlay.cpp`

- primedev/client/rejectconnectionfixes.cpp
- Honestly, this is a difficult one to test functionality for... I guess the hook being created will have to do?
> Remove uses of Autohook from `rejectconnectionfixes.cpp`

- primedev/client/modlocalisation.cpp
- Make sure that loading localisation files from mods still works as expected.
> Remove uses of Autohook from `modlocalisation.cpp`

- primedev/core/filesystem/filesystem.cpp
- Make sure that the loading mod files (scripts etc.) works as normal
> Remove uses of Autohook from `filesystem.cpp`

- primedev/core/hooks.cpp
- Make sure that arguments from `ns_startup_args.txt` are still loaded
> Remove uses of Autohook from `hooks.cpp`

- primedev/client/latencyflex.cpp
- Make sure that the convar `r_latencyflex` works as usual
> Remove uses of Autohook from `latencyflex.cpp`

- primedev/client/languagehooks.cpp
- Make sure that the logging in the language hooks still triggers and behaves normally.
> Remove uses of Autohook from `languagehooks.cpp`

- primedev/core/sourceinterface.cpp
- Make sure that `CreateInterface <SERVER/CLIENT/ENGINE>` still get logged
- Make sure that the in-game console still exists (since `InitialiseConsoleOnInterfaceCreation` gets called from `ClientCreateInterface`)
> Remove uses of Autohook from `sourceinterface.cpp`

- primedev/engine/gl_matsysiface.cpp
- Make sure that `mat_crosshair_printmaterial` still works as expected. (#763)
> Remove uses of Autohook from `gl_matsysiface.cpp`

- primedev/core/convar/convar.cpp
- primedev/core/convar/cvar.cpp
- primedev/core/convar/cvar.h
Look at code
Run commands like `help` or `find` that use `g_pCVar`.
> core: Remove use of `SourceInterface` for `CCvar`

- primedev/logging/sourceconsole.cpp
- primedev/logging/sourceconsole.h
`SourceInteface` class goes back to icepick and is not good. We have a replacement, let's use it.
When testing make sure the console can stil be opened and is being logged to.
> logging: Remove use of `SourceInterface` for `CGameConsole`

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .gitignore
- BUILD.md
Set up instructions so that compiling from commandline puts the resulting binaries in `/build/game/` to match the folder structure usually generated by Visual Studio.
Supersedes #594
> Update build instructions and CI for `build` subfolder

- Dockerfile
Just ensures that indentation is consistent and not a mix of tabs and spaces. Styling change, does not affect functionality or anything.
> Ensure whitespace indentation is consistent in Dockerfile

- .github/workflows/ci.yml
Bump clang-format-lint-action to v0.18.2 which is the newest upstream version
Also fixes current formatting issues.
Not much really, this is just a version bump
If CI passes, this is good to merge. No actual code changes.
> Bump clang-format-lint-action to v0.18.2

- .github/dependabot.yml
Adds a dependabot config to check for updates to the GitHub Actions we use and makes a PR with the version bump if a new version is found.
_None_
_None_
> Add dependabot config to check for GitHub Actions updates

- primedev/core/filesystem/filesystem.cpp
- primedev/core/filesystem/filesystem.h
- primedev/mods/modmanager.cpp
- primedev/scripts/scriptdatatables.cpp
Look at code
We use filesystem for mods so as long as your mods mount everything should be fine i think.
> core: Remove use of `SourceInterface` for `IFileSystem`

- primedev/plugins/plugins.cpp
It's logged in server.dll somewhere already I believe and doesn't make sense to repeat this for every loaded plugin
> remove useless log

- primedev/dedicated/dedicated.cpp
- Make sure that dedicated servers still gracefully close on script error instead of hard crashing.
> Remove uses of Autohook from `dedicated.cpp`

- primedev/dedicated/dedicatedmaterialsystem.cpp
- Make sure that the `-softwared3d11` launch arg still works as before? (tbh we could remove this now? Don't think I've seen anyone use it in the last 2 years)
> Remove uses of Autohook from `dedicatedmaterialsystem.cpp`

- primedev/engine/hoststate.cpp
- Check logs to make sure that all of the changed hooks are being created properly (these ones for the most part log something when they are triggered, so check for that)
- Make sure that server presence is tracking the correct port (honestly easiest to just stick some breakpoints in the code and make sure that it is reading the ConVar properly
> Remove uses of Autohook from `hoststate.cpp`

- primedev/core/filesystem/rpakfilesystem.cpp
Fixing stuff described by @Alystrasz on discord. I don't really like this behaviour as it behaves a bit differently for vanilla rpak loads and modded rpak loads, but aliasing is hacky already so meh.
> Fix rpak aliasing not working when trying to alias towards a vanilla rpak

- primedev/scripts/client/clientchathooks.cpp
- Make sure that `CHudChat_ProcessMessageStartThread` still gets called in the CLIENT squirrel VM (probably easiest to add a debug print there)
> Remove uses of Autohook from `clientchathooks.cpp`

- primedev/mods/compiled/modkeyvalues.cpp
- primedev/scripts/client/scriptmodmenu.cpp
Currently, to retrieve mod information from launcher, Squirrel VM must summon methods such as `NSGetModDescriptionByModName`, `NSGetModDownloadLinkByModName`, `NSGetModLoadPriority` etc, which all loop over the list of mods until they find the correct one (using mod name as key), which is highly ineffective: this means we need as many iterations over mods list as we need information about the mod.
To solve this problem, this PR introduces a `NSGetModsInformation`, which exposes all mod information to Squirrel VM at once, using a new `ModInfo` structure.
```javascript
global struct ModInfo
{
string name = ""
string description = ""
string version = ""
string downloadLink = ""
int loadPriority = 0
bool enabled = false
bool requiredOnClient = false
bool isRemote
array<string> conVars = []
} …
```
> refactor: Mod information

- primedev/scripts/client/scriptbrowserhooks.cpp
- Check that the "force external web browser" script flag for `OpenExternalWebBrowser` still works (i.e it opens in a separate web browser instead of the origin/steam/whatever overaly)
> scripts/client: Remove uses of Autohook from `scriptbrowserhooks.cpp`

- primedev/plugins/pluginmanager.cpp
- primedev/plugins/plugins.cpp
- primedev/plugins/plugins.h
Originally it probably worked if all plugins could be reloaded but it also just dropped all the plugins regardless of whether it can be reloaded or not.
So this pr attempts to amend that by individually reloading all the plugins instead of dropping then loading them all.
(this still doesn't really fix it since I can't get any plugin to be reloaded 💢 so that's why it's a draft)
was (wow crash)
now (wow still doesn't work!)
so basically I need some help but I think this pr is good first stepping stone. :)
ignore the screenshots before this
with this pr if upon reloading plugins nothing crashes then that means it worked as intended.
> Fix reloading plugins

- primedev/shared/misccommands.cpp
There is literally 0 reason for it to have it, especially because its ragdoll counterparts `cl_ragdoll_force_fade_time_` don't. No idea what Respawn was thinking to be honest
https://github.com/user-attachments/assets/fa32f5da-c3e0-494f-addb-1d3b064e9a94
> Remove cheat flag from `cl_gib_lifetime`

- .github/workflows/release.yml
Release CI configuration is currently broken due to deprecated actions being used in our workflow: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Failed action log: https://github.com/R2Northstar/NorthstarLauncher/actions/runs/13319580414/job/37201465885
> build: Use `actions/[download,upload]-artifact@v4` in release CI configuration

- primedev/server/serverchathooks.cpp
- Check that the chat hooks still function as expected
> server: Remove uses of Autohook from`serverchathooks.cpp`

- primedev/core/filesystem/rpakfilesystem.cpp
Reverts R2Northstar/NorthstarLauncher#521
Building [fails](https://github.com/R2Northstar/NorthstarLauncher/actions/runs/14391709815/job/40359932310) on `main`, I guess the PR waited for too long to be reviewed.
> Revert "Fix crash in `ReadFileAsync`"

- primedev/core/filesystem/rpakfilesystem.cpp
Recreation of https://github.com/R2Northstar/NorthstarLauncher/pull/521 since it got reverted.
Original description:
> Fixes a NULL dereference crash in `ReadFileAsync`
> 
> This seems to be very rare, there's currently an open [ticket](https://discord.com/channels/920776187884732556/1134199951971332096) where this occurs. This version hasnt been tested yet.
> 
> I also promised to ping `@shmordan_08` when this gets released
> 
> Closes #520
> Fix Null Deref crash

- primedev/client/r2client.cpp
- primedev/shared/exploit_fixes/exploitfixes.cpp
Set execution markers properly if there's enough room or ignore command otherwise.
Stops servers from executing commands on the client if not in vanilla.
> Set execution markers properly

- primedev/shared/playlist.cpp
The exact same thing as https://github.com/R2Northstar/NorthstarLauncher/pull/687. I know that Spoon said this should be handled in a different way, but since toggling vanilla isn't a thing right now, i don't really think it matters. If that ever changes this can just be updated.
Another part of why im making this is because i don't want people to download a random `.dll` from NexusMods to fix it https://www.nexusmods.com/titanfall2/mods/62
> fix: Add vanilla compatibility for `setplaylistvaroverride` byte-patch

- primedev/plugins/interfaces/sys/ISys.cpp
- primedev/plugins/interfaces/sys/ISys.h
With the old system it was possible to act in the name of a different plugin. For example it was possible to log something using DiscordRPC's sink by just passing the DiscordRPC handle to INSSys::Log.
To test just start the game and observe that DiscordRPC logging still works
> determine calling plugin by return address

- primedev/plugins/interfaces/IPluginCallbacks.h
adding the size allows safely adding members to the InitData struct with backwards compatibility https://github.com/torvalds/linux/blob/master/include/uapi/linux/fs.h#L562-L563
> add initdata size for backwards / forward compat
